[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "ODC2023"
dynamic = ["version"]
description = "ODC2023"
authors = ["Sped0n", "Z-MicTure"]
requires-python = ">=3.11.0"
dependencies = [
    "matplotlib",
    "numpy",
    "opencv-contrib-python",
]