name: python test

on:
  push:
    branches: [ main ]
    paths:
      - 'CV/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'CV/**'
  workflow_dispatch:

jobs:
  python-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./CV

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          architecture: 'x64'
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          pip install pytest pytest-cov
          PYTHONPATH=. pytest --junitxml=junit/test-results.xml --cov --cov-report=xml --cov-report=html
      - name: Upload pytest test results
        uses: actions/upload-artifact@v3
        with:
          name: pytest-results-3.11
          path: CV/junit/test-results.xml
        if: ${{ always() }}
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3